[bcm-refsw] bump to 15.2

diff --git a/package/bcm-refsw/S70nxserver b/package/bcm-refsw/S70nxserver
--- a/package/bcm-refsw/S70nxserver
+++ b/package/bcm-refsw/S70nxserver
@@ -2,33 +2,33 @@
 
 start() {
 	echo -n "Starting nxserver: "
-	start-stop-daemon -S -q -b -m -p /var/run/nxserver.pid -x /bin/nxserver -- -display_format 720p >/dev/null 2>&1
+	start-stop-daemon -S -q -b -m -p /var/run/nxserver.pid --exec /usr/bin/nxserver -- </dev/null >/dev/null 2>&1
 	[ $? == 0 ] && echo "OK" || echo "FAIL"
 }
 stop() {
-    echo -n "Stopping nxserver: "
-    start-stop-daemon -K -q -p /var/run/nxserver.pid
-    [ $? == 0 ] && echo "OK" || echo "FAIL"
-    rm -rf /var/run/nxserver.pid
+	echo -n "Stopping nxserver: "
+	start-stop-daemon -K -q -p /var/run/nxserver.pid
+	[ $? == 0 ] && echo "OK" || echo "FAIL"
+	rm -rf /var/run/nxserver.pid
 }
 restart() {
-    stop
-    start
+	stop
+	start
 }
 
 case "$1" in
-  start)
-    start
-    ;;
-  stop)
-    stop
-    ;;
-  restart|reload)
-    restart
-    ;;
-  *)
-    echo "Usage: $0 {start|stop|restart}"
-    exit 1
+	start)
+		start
+		;;
+	stop)
+		stop
+		;;
+	restart|reload)
+		restart
+		;;
+	*)
+		echo "Usage: $0 {start|stop|restart}"
+		exit 1
 esac
 
 exit $?
